[package]
name = "font-loader"
version = "0.1.0"
authors = ["MSleepyPanda <m.sleepypanda@gmail.com>"]
license = "MIT"
readme = "Readme.md"

[dependencies]
libc = "0.2.15"


[target.'cfg(windows)'.dependencies]
winapi = "0.2"
user32-sys = "0.2"
gdi32-sys = "0.2.0"

[target.'cfg(unix)'.dependencies]
silverknife-fontconfig-sys = "0.1.0"
