[package]
name = "font-loader"
version = "0.1.0"
authors = ["MSleepyPanda <m.sleepypanda@gmail.com>"]
license = "MIT"
readme = "Readme.md"


[dependencies]
winapi = "0.2"
user32-sys = "0.2"
gdi32-sys = "0.2.0"
libc = "0.2.15"
